### PR TITLE
FIXED Issue #34 Cannot assign Illuminate\Foundation\Application to property ZanySoft\Zip\Zip::$zip_file of type ?string

### PR DESCRIPTION
**Pull request by nabeeljavaid**
@zanysoft issue has been fixed please review my PR

### CODE REVIEW

**Review by Tarhex — APPROVED** [review]
A successful fix

**Comment by szhorvath** [comment]
@nabeeljavaid When could you merge this, please? 
This causes an issue with IDE helper. I cannot generate helper files.

**Comment by nabeeljavaid** [comment]
@zanysoft please merge my PR so other users can avoid same problem

**Comment by tharindud93** [comment]
@zanysoft can you please merege this. when I use php 8.x this change fixed my problem

**Comment by giagara** [comment]
Can this merge be done, I also have issues with php8.1

**Pull request closed without merging**
