### PR TITLE
Laravel 9 support

### PR DESCRIPTION
**Pull request by cbekir**

### CODE REVIEW

**Comment by RemCom** [comment]
@zanysoft Can you have a look at the PR

**Comment by teknology** [comment]
@RemCom Are they even responding?

**Comment by RemCom** [comment]
@teknology nobody responded yet sadly.

**Comment by ChrisToxz** [comment]
Anyone knows a fork that is/will be maintained? Currently using the fork of @cbekir, works fine but need long term solution.

**Comment by ChrisToxz** [comment]
Same situation for me. Have also a few other packages that I had to fork by myself, but prefer official sources..
Sad that developer is ignoring, there is activity after the PR & comment.

**Comment by ChrisToxz** [comment]
I just checked the activities of the forks, none of them is forked with intention to continue development.
So unfortnually I guess own forks is the only reasonable way. Don't want to trust 'random' forks neither.

**Comment by zanysoft** [comment]
Check our latest version 2.0.x

**Pull request closed without merging**
